name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install Catch2
      run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          git checkout v3.0.0-preview3
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install 

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
  
  build_cmake_installed:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Install RapidFuzz
      run: sudo cmake --build ${{github.workspace}}/build --target install

    - name: Configure example project
      working-directory: ${{github.workspace}}/examples/cmake_installed
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build example project
      working-directory: ${{github.workspace}}/examples/cmake_installed
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run example project
      working-directory: ${{github.workspace}}/examples/cmake_installed/build
      run: foo
